### ISSUE TITLE
Unable to ssh into ec2-instance

### ISSUE THREAD

**Issue by yongkyunlee** [testdrivenio/django-ecs-terraform#7]
I was unable to ssh into an ec2-instance running in ECS cluster (operation timeout error).
When I changed the target of the VPC route table 0.0.0.0/0 to Internet Gateway of the VPC from the NAT Gateway, I could access the ec2-instance. I could not figure out why this was happening.
When I change the target to NAT Gateway again, the whole system works as expected.

**Comment by javier-caylent** [comment]
Maybe you'll need allow the ssh protocol on the vpc acl and also to the security group of the ec2 instance, if you are trying to reach it trought internet, please add your public ip

**Comment by alexhutnik** [comment]
It might be a fluke that switching back to NAT gateway fixes the problem due to stale states in the route table. Overall, it should not be possible to directly SSH in to hosts in a properly configured private subnet (hence why the subnet is **private**). The difference between a private and public subnet is that the former has a NAT Gateway and the latter an Internet Gateway. When you added the IGW you effectively made that a public subnet. So, one modification I would add to this article is adding a bastion host to the public subnet and modifying the networking and SG configs to allow SSH to the bastion and from the bastion to anything in the private subnet.

**Comment by SootyOwl** [comment]
This issue still exists - cloning this repo and following the instructions provided in the README ends up in a state where the EC2 instances aren't open to SSH.
